AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Book details of a visit, using Amazon Lex to perform natural language
  understanding
Resources:
  mytest:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: >-
        Book details of a visit, using Amazon Lex to perform natural language
        understanding
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::468412006895:role/LambdaDynamoDBRole'
      Tags:
        'lambda-console:blueprint': lex-book-trip-python
      Layers:
        - >-
          arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python27-SciPy1x:24
        - 'arn:aws:lambda:us-east-1:468412006895:layer:layer-requests:3'
